<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Jenis as JenisModel;

class Jenis extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        JenisModel::insert([
            ['kode' => 'BRD', 'jenis' => 'BusinessRequirementDocument', 'category_id' => '2'],
            ['kode' => 'DRST', 'jenis' => 'DraftRencanaStrategisTI', 'category_id' => '1'],
            ['kode' => 'PAI', 'jenis' => 'UsulanPenyusunanArsitekturInformasi', 'category_id' => '1'],
            ['kode' => 'RRST', 'jenis' => 'HasilReviewRencanaStrategisTI', 'category_id' => '1'],
            ['kode' => 'RST', 'jenis' => 'RencanaStrategisTI', 'category_id' => '1'],
            ['kode' => 'MRK', 'jenis' => 'HasilMonitoringPelaksanaanRencanaKerjadanAng', 'category_id' => '1'],
            ['kode' => 'RSP', 'jenis' => 'RiskProfile', 'category_id' => '1'],
            ['kode' => 'MRP', 'jenis' => 'LaporanMonitoringRiskProfile', 'category_id' => '1'],
            ['kode' => 'MTR', 'jenis' => 'RekomendasiPenerapanMitigasiRisiko', 'category_id' => '1'],
            ['kode' => 'PRR', 'jenis' => 'LaporanPenerapanRekomendasiRisiko', 'category_id' => '1'],
            ['kode' => 'KSD', 'jenis' => 'LaporanKebutuhanSDMTI', 'category_id' => '1'],
            ['kode' => 'UTR', 'jenis' => 'UsulanTrainingTI', 'category_id' => '1'],
            ['kode' => 'JTR', 'jenis' => 'JadwalTrainingTI', 'category_id' => '1'],
            ['kode' => 'PKT', 'jenis' => 'PerencanaanKapasitasTI', 'category_id' => '1'],
            ['kode' => 'MKH', 'jenis' => 'LaporanMonitoringKapasitasHardware', 'category_id' => '1'],
            ['kode' => 'PKP', 'jenis' => 'HasilMonitoringPelaksanaanKebijakandanProsedu', 'category_id' => '1'],
            ['kode' => 'UKP', 'jenis' => 'UsulanKebutuhanProyekTI', 'category_id' => '1'],
            ['kode' => 'PPT', 'jenis' => 'ProjectPlan', 'category_id' => '1'],
            ['kode' => 'MPT', 'jenis' => 'LaporanMonitoringProyekTI', 'category_id' => '1'],
            ['kode' => 'PKPT', 'jenis' => 'LaporanPengukuranKinerjaProyekTI', 'category_id' => '1'],
            ['kode' => 'MPJ', 'jenis' => 'LaporanMonitoringPenyediaJasaTI', 'category_id' => '1'],
            ['kode' => 'MKP', 'jenis' => 'MemoKompensasi', 'category_id' => '1'],
            ['kode' => 'RHA', 'jenis' => 'ResumeHasilAudit', 'category_id' => '1'],
            ['kode' => 'LHA', 'jenis' => 'LaporanHasilAudit', 'category_id' => '1'],
            ['kode' => 'LMR', 'jenis' => 'LaporanMonitoringRekomendasi', 'category_id' => '1'],
            ['kode' => 'RPG', 'jenis' => 'PermintaanPengembangan', 'category_id' => '2'],
            ['kode' => 'SKL', 'jenis' => 'StudiKelayakan', 'category_id' => '2'],
            ['kode' => 'IJP', 'jenis' => 'IzinPrinsip', 'category_id' => '2'],
            ['kode' => 'PPK', 'jenis' => 'PermohonanPengadaanPerangkatKeras', 'category_id' => '2'],
            ['kode' => 'FSD', 'jenis' => 'FunctionalSpesificationDesign', 'category_id' => '2'],
            ['kode' => 'SOW', 'jenis' => 'ScopeofWorks', 'category_id' => '2'],
            ['kode' => 'SIT', 'jenis' => 'SystemIntegrationTestingScript', 'category_id' => '2'],
            ['kode' => 'BAS', 'jenis' => 'BeritaAcaraSIT', 'category_id' => '2'],
            ['kode' => 'UAT', 'jenis' => 'UserAcceptanceTestScript', 'category_id' => '2'],
            ['kode' => 'BAT', 'jenis' => 'BeritaAcaraUAT', 'category_id' => '2'],
            ['kode' => 'CR-INT', 'jenis' => 'ChangeRequest', 'category_id' => '2'],
            ['kode' => 'IIS', 'jenis' => 'InstallationInstruction', 'category_id' => '2'],
            ['kode' => 'LPM', 'jenis' => 'LaporanImplementasi', 'category_id' => '2'],
            ['kode' => 'BAM', 'jenis' => 'BeritaAcaraImplementasiSistemAplikasi', 'category_id' => '2'],
            ['kode' => 'PIRC', 'jenis' => 'PostImplementasiReviewChecklist', 'category_id' => '2'],
            ['kode' => 'ILG', 'jenis' => 'IssueLogs', 'category_id' => '2'],
            ['kode' => 'PIRR', 'jenis' => 'PostImplementationReviewReport', 'category_id' => '2'],
            ['kode' => 'LPS', 'jenis' => 'LaporanPemeliharaanSistemAplikasi', 'category_id' => '2'],
            ['kode' => 'LAD', 'jenis' => 'LaporanAnalisaDampak', 'category_id' => '2'],
            ['kode' => 'CBD', 'jenis' => 'ChecklistBackupData', 'category_id' => '2'],
            ['kode' => 'CRD', 'jenis' => 'PermohonanPerubahan(CR)Darurat', 'category_id' => '2'],
            ['kode' => 'CLG', 'jenis' => 'ChangeLog', 'category_id' => '2'],
            ['kode' => 'PPU', 'jenis' => 'BeritaAcaraPenyerahanPowerUser', 'category_id' => '4'],
            ['kode' => 'STP', 'jenis' => 'BeritaAcaraSerahTerimaPerangkatJaringan', 'category_id' => '3'],
            ['kode' => 'PID', 'jenis' => 'PenyerahanUserIDBaru', 'category_id' => '4'],
            ['kode' => 'MHL', 'jenis' => 'LaporanMonitoringPengamananInformasi', 'category_id' => '4'],
            ['kode' => 'LPK', 'jenis' => 'LaporanPenetapanKlasifikasiInformasi', 'category_id' => '4'],
            ['kode' => 'LPD', 'jenis' => 'LaporanPenangananInsiden', 'category_id' => '3'],
            ['kode' => 'LPP', 'jenis' => 'LaporanPenangananMasalah', 'category_id' => '3'],
            ['kode' => 'PPC', 'jenis' => 'PermohonanPengujianPatch', 'category_id' => '3'],
            ['kode' => 'BAP', 'jenis' => 'BeritaAcaraInstalasiPatch', 'category_id' => '3'],
            ['kode' => 'PRM', 'jenis' => 'PermohonanPerubahanParameter', 'category_id' => '3'],
            ['kode' => 'BAK', 'jenis' => 'BeritaAcaraImplementasiKonfigurasi', 'category_id' => '3'],
            ['kode' => 'BAC', 'jenis' => 'BeritaAcaraBackup', 'category_id' => '3'],
            ['kode' => 'P3K', 'jenis' => 'PermohonanPengadaanPerangkatKeras', 'category_id' => '3'],
            ['kode' => 'INV', 'jenis' => 'DaftarInventarisasiAsetTI', 'category_id' => '3'],
            ['kode' => 'DSP', 'jenis' => 'PermohonanDisposal', 'category_id' => '3'],
            ['kode' => 'BAD', 'jenis' => 'BeritaAcaraDisposal', 'category_id' => '3'],
            ['kode' => 'PAT', 'jenis' => 'PemeliharaanAsetTI', 'category_id' => '3'],
            ['kode' => 'PPJ', 'jenis' => 'PermohonanPenambahanJaringan', 'category_id' => '3'],
            ['kode' => 'PMJ', 'jenis' => 'PermohonanImplementasiJaringan', 'category_id' => '3'],
            ['kode' => 'BAJ', 'jenis' => 'BeritaAcaraPemasanganJaringan', 'category_id' => '3'],
            ['kode' => 'LPPI', 'jenis' => 'LaporanPenangananInsidenPengamananInformasi', 'category_id' => '4'],
            ['kode' => 'PSD', 'jenis' => 'PenghapusanUserID', 'category_id' => '4'],
            ['kode' => 'PBU', 'jenis' => 'PenyerahanPerubahanUser', 'category_id' => '4'],
            ['kode' => 'PWR', 'jenis' => 'PermohonanPenggunaanPowerUser', 'category_id' => '4'],
            ['kode' => 'BPWR', 'jenis' => 'BeritaAcaraPenggunaanPowerUser', 'category_id' => '4'],
            ['kode' => 'ADC', 'jenis' => 'PermohonanAkseskeDataCenter', 'category_id' => '4'],
            ['kode' => 'LDC', 'jenis' => 'LogBookDataCenter', 'category_id' => '4'],
            ['kode' => 'PHA', 'jenis' => 'PenyerahanHakAkseskeDatabasedanInfrastruktur', 'category_id' => '4'],
            ['kode' => 'LLOG', 'jenis' => 'LaporanReviewLogAksesLogis', 'category_id' => '4'],
            ['kode' => 'LLDC', 'jenis' => 'LaporanReviewLogAksesDataCenter', 'category_id' => '4'],
            ['kode' => 'PDT', 'jenis' => 'PermintaanData', 'category_id' => '5'],
            ['kode' => 'RSTR', 'jenis' => 'Restore', 'category_id' => '5'],
            ['kode' => 'PMC', 'jenis' => 'PemeliharaanAplikasiEndUserComputing', 'category_id' => '7'],
            ['kode' => 'PGC', 'jenis' => 'PengembanganAplikasiEndUserComputing', 'category_id' => '7'],
            ['kode' => 'VPN', 'jenis' => 'BeritaAcaraSerahTerimaUserVPN', 'category_id' => '3'],
            ['kode' => 'STT', 'jenis' => 'StressTesting', 'category_id' => '2'],
            ['kode' => 'FPHA', 'jenis' => 'PermintaanHakAkses', 'category_id' => '4'],
            ['kode' => 'BAMS', 'jenis' => 'BeritaAcaraMigrasiServer', 'category_id' => '3'],
            ['kode' => 'BASTD', 'jenis' => 'BeritaAcaraSerahTerimaDevelopment', 'category_id' => '3'],
            ['kode' => 'PCKB', 'jenis' => 'PenyerahanCredentialKeyBaru', 'category_id' => '3'],
            ['kode' => 'PPL', 'jenis' => 'PermohonanPerangkatLunak', 'category_id' => '3'],
            ['kode' => 'LMBJ', 'jenis' => 'LaporanMonitoringBandwithJaringan', 'category_id' => '3'],
            ['kode' => 'PPD', 'jenis' => 'PermohonanPerubahanDarurat', 'category_id' => '3'],
            ['kode' => 'SRD', 'jenis' => 'ServerRequestDocument', 'category_id' => '3'],
            ['kode' => 'BASK', 'jenis' => 'BeritaAcaraSerahTerimaKredensial', 'category_id' => '3'],
        ]);
    }
}
